import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Head } from '@inertiajs/react';
import { ArrowRight, BookOpen, Braces, CheckCircle2, Database, ExternalLink, FileCheck2, GitBranch, HeartHandshake, Languages, LockKeyhole, Network, Route, ShieldCheck, Sparkles, WifiOff } from 'lucide-react';

type Source = { id:string; organisation:string; title:string; url:string; language:string; category:string; reuse_status:string; last_verified:string };
type Classification = { request_id:string; status:string; reason?:string; message?:string; category?:{slug:string;label:string}; resources:Source[]; confidence_band?:string; explanation_available:boolean };

const categories = [
    ['antenatal-appointments','Antenatal appointments','Registered information about antenatal care and appointments.'],
    ['birth-place-choices','Birth-place choices','Resources about options to discuss with a maternity team.'],
    ['labour-preparation','Labour preparation','Learning resources about labour and birth preparation.'],
    ['pain-relief-information','Pain-relief information','Registered resources describing pain-relief information.'],
    ['after-birth-postnatal','After birth and postnatal','Information about the period after birth and postnatal checks.'],
    ['feeding-support','Feeding support','Breastfeeding and bottle-feeding support resources.'],
] as const;
const navigation = [['/','Navigator'],['/sources','Sources'],['/how-it-works','How it works'],['/evidence','Evidence'],['/api-docs','API']] as const;

function AppHeader({locale,setLocale}:{locale:string;setLocale:(value:string)=>void}) {
    const path=window.location.pathname;
    return <><div className="status-strip"><div className="container"><span className="status-dot"/>Portfolio demonstration · Curated source browsing is available · Model routing awaits independent review</div></div><header className="site-header"><div className="container nav-row">
        <a className="brand" href="/"><span className="brand-mark"><Route size={19}/></span><span>Maternity Learning Navigator</span></a>
        <nav className="nav-links" aria-label="Primary navigation">{navigation.map(([href,label])=><a className="nav-link" aria-current={path===href?'page':undefined} href={href} key={href}>{label}</a>)}</nav>
        <label className="sr-only" htmlFor="language">Question language</label><select id="language" className="language-select" value={locale} onChange={e=>setLocale(e.target.value)}><option value="en">English</option><option value="ckb">Kurdish Sorani · review pending</option></select>
    </div></header></>;
}

function RouterPanel({locale,online}:{locale:string;online:boolean}) {
    const [question,setQuestion]=useState(''); const [result,setResult]=useState<Classification|null>(null); const [busy,setBusy]=useState(false);
    const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setResult(null);try{const response=await fetch('/api/v1/classifications',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({question,locale})});setResult(await response.json());}finally{setBusy(false);}};
    return <div className="router-card"><h2>Ask a learning question</h2><p>The router identifies a topic and points to registered sources. It never writes a clinical answer.</p><form onSubmit={submit}>
        <label className="sr-only" htmlFor="question">Your maternity learning question</label><textarea id="question" className="question-field" dir={locale==='ckb'?'rtl':'ltr'} maxLength={500} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={locale==='ckb'?'Sorani free text remains locked pending qualified review.':'For example: What happens at antenatal appointments?'}/>
        <div className="field-meta"><span>Questions are processed transiently and not stored</span><span>{question.length}/500</span></div><button className="primary-button" type="submit" disabled={!online||busy||question.trim().length<3}>{busy?'Checking release gate…':<>Find learning resources <ArrowRight size={17}/></>}</button>
    </form>{!online&&<div className="offline-note"><WifiOff size={16}/>Offline mode provides the cached source directory only. Classification is disabled.</div>}{locale==='ckb'&&<div className="gate-note"><Languages size={16}/>Sorani content and routing remain unavailable until a qualified reviewer signs the language gate.</div>}
    {result&&<div className="result-panel" role="status"><strong>{result.reason==='review_gate_pending'?'Release gate working as designed':result.status==='safety_bypass'?'Generic safety route activated':result.status==='low_confidence'?'No confident topic match':result.status==='unsupported'?'Outside the released router':result.category?.label}</strong><p>{result.message??'Registered resources for this educational topic are listed below.'}</p>{result.resources?.map(source=><a className="resource-mini" href={source.url} target="_blank" rel="noreferrer" key={source.id}>{source.title}<span>{source.organisation} · {source.language}</span></a>)}</div>}</div>;
}

function Home({locale,online}:{locale:string;online:boolean}) { return <main><div className="container hero"><div><span className="eyebrow"><Sparkles size={15}/>Transparent multilingual NLP</span><h1>Trusted learning paths, not generated advice.</h1><p className="hero-copy">A privacy-first portfolio prototype that routes maternity education questions to traceable resources and makes its AI boundaries visible.</p><div className="trust-row"><span className="trust-chip"><ShieldCheck size={15}/>No diagnosis or triage</span><span className="trust-chip"><Database size={15}/>No raw-question storage</span><span className="trust-chip"><FileCheck2 size={15}/>Source-level provenance</span></div></div><RouterPanel locale={locale} online={online}/></div>
    <section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Browse without classification</span><h2>Six carefully bounded topics</h2></div><p>Until human review is complete, these cards provide direct category browsing without presenting a model prediction.</p></div><div className="category-grid">{categories.map(([slug,label,description],index)=><a className="category-card" href={`/sources?category=${slug}`} key={slug}><span className="category-number">0{index+1}</span><h3>{label}</h3><p>{description}</p><span className="source-link">View registered sources →</span></a>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Engineering evidence</span><h2>Designed to fail closed</h2></div><p>Unavailable reviews, models or services lead to an explicit refusal—never a plausible-sounding maternity answer.</p></div><div className="evidence-grid"><div className="evidence-card"><LockKeyhole/><h3>Human gates first</h3><p>Sorani and clinical-safety approval are required before public free text can be enabled.</p></div><div className="evidence-card"><Network/><h3>PHP ↔ Python bridge</h3><p>Laravel owns public contracts and provenance; a private FastAPI service owns model inference and LIME.</p></div><div className="evidence-card"><WifiOff/><h3>Restricted offline mode</h3><p>The PWA caches source metadata and the interface, never questions or copied clinical guidance.</p></div></div></div></section></main>; }

function Sources() { const [sources,setSources]=useState<Source[]>([]); const category=new URLSearchParams(window.location.search).get('category'); useEffect(()=>{fetch(`/api/v1/resources${category?`?category=${encodeURIComponent(category)}`:''}`).then(r=>r.json()).then(body=>setSources(body.data??[]));},[category]); return <main className="container"><div className="page-hero"><span className="eyebrow"><BookOpen size={15}/>Provenance first</span><h1>Registered source directory</h1><p>Links, language, use status and verification dates are shown without reproducing clinical prose.</p></div><div className="source-grid">{sources.map(source=><article className="source-card" key={source.id}><span className="org">{source.organisation}</span><h3>{source.title}</h3><div className="source-meta"><span className="tag">{source.language}</span><span className="tag">{source.reuse_status.replaceAll('_',' ')}</span><span className="tag">Checked {source.last_verified}</span></div><a className="source-link" href={source.url} target="_blank" rel="noreferrer">Open original <ExternalLink size={13}/></a></article>)}</div></main>; }

function Evidence() { const coverage=[{label:'English candidates',value:12,width:80},{label:'Sorani candidates',value:3,width:20},{label:'Training eligible',value:0,width:0}]; return <main className="container"><div className="page-hero"><span className="eyebrow"><FileCheck2 size={15}/>Evidence before claims</span><h1>Technical and governance evidence</h1><p>Metrics are published only after the governed dataset, language review, clinical-safety review and leakage-safe evaluation all pass.</p></div><div className="evidence-grid"><div className="evidence-card"><div className="metric">24</div><div className="metric-label">Registered sources</div></div><div className="evidence-card"><div className="metric">15</div><div className="metric-label">Candidate questions</div></div><div className="evidence-card"><div className="metric">0</div><div className="metric-label">Training-eligible rows</div></div></div>
    <section className="section two-column"><div className="content-card"><h2>Dataset state</h2><div className="bar-list">{coverage.map(item=><div className="bar-row" key={item.label}><span>{item.label}</span><div className="bar-track"><div className="bar-fill" style={{width:`${item.width}%`}}/></div><strong>{item.value}</strong></div>)}</div></div><div className="locked-panel"><h3><LockKeyhole size={19}/>Model results locked</h3><p>Confusion matrices, macro-F1, calibration and baseline-versus-XLM-R results will appear here only after approved bilingual training data exists.</p><p className="notice">No performance result has been estimated, back-filled or fabricated.</p></div></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">Vacancy alignment</span><h2>One project, full lifecycle</h2></div></div><div className="evidence-grid">{[['PHP · MySQL · APIs','Laravel 13, MySQL 8.4, versioned REST and read-only GraphQL.'],['Python · deep learning','A gated FastAPI pipeline for TF-IDF and XLM-R training and deployment.'],['Responsible XAI','Transient LIME explanations with non-causal limitations and no token retention.'],['Cloud · offline','Portable containers, private service networking and a restricted PWA cache.'],['Data pipeline','Provenance, review states, leakage-safe splits, checksums and model cards.'],['Multilingual UI','BCP-47 Sorani input and RTL behavior are implemented behind a mandatory qualified review gate.']].map(([title,text])=><div className="evidence-card" key={title}><CheckCircle2 size={18}/><h3>{title}</h3><p>{text}</p></div>)}</div></section></main>; }

function HowItWorks(){return <main className="container"><div className="page-hero"><span className="eyebrow"><Network size={15}/>Bounded by design</span><h1>How the navigator works</h1><p>The application separates user experience, provenance, model inference and review evidence so each can fail safely.</p></div><div className="two-column"><div className="content-card"><h2>1. Laravel receives the question</h2><p>It validates length and locale, checks the release gates and creates a random request ID. Request bodies are excluded from logs.</p></div><div className="content-card"><h2>2. FastAPI routes—not answers</h2><p>The private service may select an educational category only when an approved model artifact is present.</p></div><div className="content-card"><h2>3. MySQL returns provenance</h2><p>The category resolves to registered source links with organisation, language, licence status and verification date.</p></div><div className="content-card"><h2>4. LIME is optional</h2><p>Local token weights explain the routing model and are discarded immediately after the response.</p></div></div><section className="section"><div className="content-card"><h2>Regulatory boundary</h2><p>This educational portfolio prototype does not assess a person, recommend an action, predict an outcome or claim NHS, MHRA or DCB0129 approval.</p></div></section></main>}

function ApiDocs(){const example=`POST /api/v1/classifications\nContent-Type: application/json\n\n{\n  "question": "What happens at antenatal appointments?",\n  "locale": "en"\n}`;return <main className="container"><div className="page-hero"><span className="eyebrow"><Braces size={15}/>Versioned interfaces</span><h1>REST and GraphQL APIs</h1><p>The public API is narrow: classification stores only derived metadata and GraphQL is read-only.</p></div><div className="two-column"><div className="content-card"><h2>REST</h2><ul><li>POST classifications</li><li>POST on-demand explanation</li><li>GET resources and model card</li><li>POST fixed-choice feedback</li></ul><pre className="code-block">{example}</pre></div><div className="content-card"><h2>GraphQL</h2><ul><li>categories(locale)</li><li>resources(category, locale)</li><li>source(code)</li><li>modelVersion</li></ul><p>Query depth and complexity are limited. No GraphQL mutation can invoke the model.</p><a className="secondary-button" href="/api/v1/openapi.json">OpenAPI JSON <ExternalLink size={15}/></a></div></div></main>}

function PolicyPage({type}:{type:'privacy'|'accessibility'}){const privacy=type==='privacy';return <main className="container"><div className="page-hero"><span className="eyebrow">{privacy?<ShieldCheck size={15}/>:<HeartHandshake size={15}/>} {privacy?'Data minimisation':'Inclusive by default'}</span><h1>{privacy?'Privacy and intended use':'Accessibility statement'}</h1><p>{privacy?'The application demonstrates useful telemetry without retaining the question that produced it.':'The interface targets WCAG 2.2 AA and includes explicit testing for RTL and bidirectional text.'}</p></div><div className="two-column">{privacy?<><div className="content-card"><h2>What may be stored</h2><ul><li>Random request ID</li><li>Locale and routed category</li><li>Model version, confidence band and latency</li><li>Fixed-choice helpfulness feedback</li></ul></div><div className="content-card"><h2>What is not stored</h2><ul><li>Raw questions or LIME tokens</li><li>Names, contact details or symptoms</li><li>Patient records or special-category datasets</li><li>Free-text feedback</li></ul></div></>:<><div className="content-card"><h2>Implemented</h2><ul><li>Keyboard-visible focus</li><li>Reduced-motion support</li><li>Responsive text and layout</li><li>Semantic headings and landmarks</li><li>RTL-capable question input</li></ul></div><div className="content-card"><h2>Release gate</h2><p>Automated checks are not certification. Manual keyboard, zoom, contrast, screen-reader and Sorani bidirectional-text tests remain required.</p></div></>}</div></main>}

function Footer(){return <footer className="site-footer"><div className="container footer-row"><div><strong>Maternity Learning Navigator</strong><br/>Independent portfolio prototype by Karlo Nahro.</div><div className="footer-links"><a href="/privacy">Privacy</a><a href="/accessibility">Accessibility</a><a href="/evidence">Evidence</a><a href="https://github.com/Karlo612" target="_blank" rel="noreferrer"><GitBranch size={14}/>GitHub</a></div></div></footer>}

export default function Navigator(){const [locale,setLocale]=useState(()=>localStorage.getItem('navigator-locale')??'en');const [online,setOnline]=useState(navigator.onLine);useEffect(()=>{localStorage.setItem('navigator-locale',locale);document.documentElement.dir='ltr';},[locale]);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);const path=window.location.pathname;const content=useMemo(()=>path==='/sources'?<Sources/>:path==='/evidence'?<Evidence/>:path==='/how-it-works'?<HowItWorks/>:path==='/api-docs'?<ApiDocs/>:path==='/privacy'?<PolicyPage type="privacy"/>:path==='/accessibility'?<PolicyPage type="accessibility"/>:<Home locale={locale} online={online}/>,[path,locale,online]);return <div className="app-shell" dir="ltr"><Head title="Maternity Learning Navigator"/><AppHeader locale={locale} setLocale={setLocale}/>{content}<Footer/></div>}
